### ISSUE TITLE
Add Blogs

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Aryankpoor/Order-delivery#13]
@Aryankpoor Assign This issue to me under Hacktoberfest

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana what will you be doing in this ?

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana what will you be doing in this ?

@Aryankpoor I thought you may be doing any Freelancing work so might Writes Any Blogs Related your Work That's Why I have Added It, Its Just Like May be you have company, As it is a product tracking wesite Then Must be Its A company Or A service, May be That Has Some Blogs Related To Company or That Service That's why i have Added It

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana I don't think blog is required and anyway related to the repo. It's just a project I made in free time . I am closing this issue for now

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana I don't think blog is required and anyway related to the repo. It's just a project I made in free time . I am closing this issue for now

@Aryankpoor Thik Sir Baki 3 Issues kahe Chhod diye uskoo bhi ssign kardo including You Also... Kuch Numbers Hai jo pure kRnee haii that's why... Now m started just doing your work Project last PR Tha Raise karadiya... abhhii apkaa karta hun sir bass bakin3 bhhi krdoo...

**Comment by Kapileswar-Moharana** [comment]
> > @Kapileswar-Moharana I don't think blog is required and anyway related to the repo. It's just a project I made in free time . I am closing this issue for now
> 
> @Aryankpoor Thik Sir Baki 3 Issues kahe Chhod diye uskoo bhi ssign kardo including You Also... Kuch Numbers Hai jo pure kRnee haii that's why... Now m started just doing your work Project last PR Tha Raise karadiya... abhhii apkaa karta hun sir bass bakin3 bhhi krdoo...

@Aryankpoor One more thing m addding photos manually app badd main appne hisab see laga lenaa... ok..

**Comment by Aryankpoor** [comment]
ok
