### ISSUE TITLE
Add Favicon  icon As per the Project Name

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Aryankpoor/Order-delivery#16]
@Aryankpoor Assign this issue to me under Hacktoberfest

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana make sure to use uncopyrighted favicon

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana make sure to use uncopyrighted favicon

Sure Sir
