### ISSUE TITLE
Accept All these PR Request Sir then Other Issues will work on these Code

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Aryankpoor/Order-delivery#34]
@Aryankpoor Accept these PR Sir..

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana Wait. There are some conflicts in the html and css files of the PRs you have made which I need to fix otherwise I will not be able to merge these PRs

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana Wait. There are some conflicts in the html and css files of the PRs you have made which I need to fix otherwise I will not be able to merge these PRs

Okay... But there should not be Any Conflicts... May be that i have created Different branches for different sections.. may be the code places .. creating conflicts...

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana all PRs have been merged. Meanwhile we should work on the currently opened issues before opening new ones. I am closing this issue now.

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana all PRs have been merged. Meanwhile we should work on the currently opened issues before opening new ones. I am closing this issue now.

ok sirr...
