### ISSUE TITLE
UI issues with website

### ISSUE THREAD

**Issue by Aryankpoor** [Aryankpoor/Order-delivery#37]

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor What Type of UI Issue?

**Comment by ankit-ask** [comment]
Issues fixed in this PR:

https://github.com/Aryankpoor/Order-delivery/pull/36

**Comment by Kapileswar-Moharana** [comment]
> Issues fixed in this PR:
> 
> #36

@ankit-ask Could you once Lokk Out the website Hosted by this.. Project how it's looks Now... And How i made it ?


https://github.com/Aryankpoor/Order-delivery/assets/129049677/a6fcdd0e-44f6-4773-ac41-875fd4812197

**Comment by Aryankpoor** [comment]
@ankit-ask PR #36 has already been merged

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana #44 has also been merged. Closing this issue as it has been resolved
