### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Aryankpoor/Order-delivery#5]
Add a Dark mode to the Tracker Website.

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Assign This Task To me I will Update The Changes, Assign this to me under Hacktoberfest'23.

**Comment by Aryankpoor** [comment]
I was also working on this for some time but I was not able to tackle one issue. Try if you can make a button in the same website to switch to dark mode

**Comment by Kapileswar-Moharana** [comment]
ok

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Can I Change the overall Look And Functionalities

**Comment by Aryankpoor** [comment]
Yes . I will approve it later

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor So now what should I do, Do I work on that issue, if ii add a section and another section that looks different as its now, First of All, You Check it then after you can assign me other Issues.

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor First Of All I worked on assigned issues and open Pr By tonight ok

**Comment by Aryankpoor** [comment]
Look. You can change the overall look and functionality. If there is anything wrong in it I will tell you to change it otherwise it will get merged.

**Comment by Kapileswar-Moharana** [comment]
> Look. You can change the overall look and functionality. If there is anything wrong in it I will tell you to change it otherwise it will get merged.

Sir Can you just call me 9348534793 it will sme how better I think to make you understand

**Comment by Kapileswar-Moharana** [comment]
> Look. You can change the overall look and functionality. If there is anything wrong with it I will tell you to change it otherwise it will get merged.
### @Aryankpoor Look Sir actually I am asking you to call me bcz of only to know the project plan that how actually wanted to make it, 
**My plan**
 - Create A Home page For Shipment/Transport Services
 - Add Nav Bar To it 
 - Add Dark Mode To it
 - Add Services To it
 - Add Blogs To it
 - Add Footer Section
 - Add Back To to Button 
 - Add Favicon Icon As per the project name 
 - Add Privacy Policy
 - In the Footer section 
        - Contact us Section
        - track Your Shipment(With Progress Button Like You Created)
        - etc. etc.

### here are some Screenshots 
![Screenshot 2023-10-24 014049](https://github.com/Aryankpoor/Order-delivery/assets/129049677/d4662d98-9c96-44a9-9f4d-752f430b4286)


![Screenshot 2023-10-24 014106](https://github.com/Aryankpoor/Order-delivery/assets/129049677/ac18c7d6-5834-4e08-8365-db0cccff5f5f)

![Screenshot 2023-10-24 014124](https://github.com/Aryankpoor/Order-delivery/assets/129049677/725310b9-81b8-43aa-805d-37a154f4d0e6)


![Screenshot 2023-10-24 014131](https://github.com/Aryankpoor/Order-delivery/assets/129049677/f345d96f-d936-42ff-aa05-1c273f2c1df4)


![Screenshot 2023-10-24 014145](https://github.com/Aryankpoor/Order-delivery/assets/129049677/2895244b-7f92-458d-8d7b-302770f7fc31)




![Screenshot 2023-10-24 014202](https://github.com/Aryankpoor/Order-delivery/assets/129049677/e0e09b82-4359-4f88-8ad7-9b3e7e65dfd9)

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor it's a prebuilt project of mine I never posted it anywhere so if you say yes then I will just slightly update it and open PR by this morning. Don't worry your codes will update behind the Track Your Shipment section with a slight updation.

Then I am Opening issues on the Following section Just do One favour for me Just Assignen me including you also all the issues 
to make Please ...Today 12 'O' Clock is the deadline i will do all these before that please you please assign me these issues including adding the list of hacktoberfest and hacktoberfest accepted.

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor If any extra Changes you want then tell me I will update those functionalities please sir assign me these issues including you then after I will start opening pr separately for separate issues.

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor ? Say Something

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana fine. Do the changes and make a PR

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana fine. Do the changes and make a PR

@Aryankpoor Thnks Man OK then you will assign the mentioned issues right now or, I am Gonna Make PR Differently for the mentioned Issues, At a time you just assigned and Add The Lebel To it ... Ok Then start preparing now to Making PR ... You Just be Available to check it out

**Comment by Aryankpoor** [comment]
Show screenshots for dark mode also @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor bhai sir kya boluu app pehlee Homepage PR merge kijiyee uskii wajsee bakii sabb atka padaa haii? #18

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor You merged all of the codes randomly one after another so it looks like broken...now

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana what looks broken?

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Click on the Live link of your website you can see itself.. Wait be online for 10 mins I am Raising PR

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Sir Can You Please Check out the Previous Raised Two Issues As codes being Broken After i don't Know how it's May be because of
- Raising Multiple PR At a Time
- Which May Cause Conflicts...Or Error...
- So This Time I am Trying To Raise the PR From Patch directly Means pasting my Local Codes in Master Branch Directly.
- Can You Please Check it Out

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Dark Mode Codes and The Feadback Form Codes That i have already commented on the Previous Codes In order to not creating new issues, So Check These Code if it's Working Well or if not then its.. ok after Finishing all Assigned issues Again I will work upon these Codeto working well , if there any error left..? So For Now @Aryankpoor Check it Sir?

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Check The PR #47
