### ISSUE TITLE
Issue in dark mode

### ISSUE THREAD

**Issue by akshitjain2004** [Aryankpoor/Order-delivery#53]
On page - https://order-trackerr.netlify.app/shipment/#
The background color is not changed in dark mode. Also, i cant go back to the homepage from the above-mentioned page.

Image Proof -
![image](https://github.com/Aryankpoor/Order-delivery/assets/94056853/e25da698-77ee-4c88-9c99-74e09475ff60)

Assign this issue to me. I'll do it

**Comment by akshitjain2004** [comment]
Solved the issue. Changed placeholder's div background to none.
![image](https://github.com/Aryankpoor/Order-delivery/assets/94056853/a1f93011-1b01-41a4-9f33-a3c249e54a94)

**Comment by Aryankpoor** [comment]
Closing this as pr related to this issue has been merge. WIll mention PR no. also.
