### ISSUE TITLE
Feedback and Support

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Aryankpoor/Order-delivery#7]
Provide a way for users to leave feedback or contact customer support for inquiries or issues related to their orders.

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Assign this work to me under Hacktoberfest'23

**Comment by Aryankpoor** [comment]
Add a link in the page to a seperate page named "Customer Support" or "Feedback page" . With UI similar to the order tracking page.

**Comment by Aryankpoor** [comment]
Use the orginal project👇 as reference for UI
https://codepen.io/codewitharyann/pen/poERmEM

**Comment by Aryankpoor** [comment]
Work on the branch I have created for all your issues

**Comment by Kapileswar-Moharana** [comment]
ok

**Comment by Aryankpoor** [comment]
Customer support should have a text form in which user can type their issue. This should be in a seperate webpage. Create a seperate folder named feedback and support in which your html css files related to this are present and I will host a website from the folder and later link it to contact us section in navbar of homepage. The frontend part of the form should only be worked on for now. Backend is an issue for later.
