### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Aryankpoor/Order-delivery#8]
If your website serves a global audience, consider offering multiple language options and local currency conversion for pricing.

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Assign this work to me under Hacktoberfest'23

**Comment by Aryankpoor** [comment]
I don't think language support is required with inbuilt web browser translation tools in apps already present. Currency conversion is not required as the website does not serve a global audience. Closing this issue now.
