### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Aryankpoor/Order-delivery#9]
Include a privacy policy to inform users about how their data is collected and used.

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Assign this work to me under Hacktoberfest'23

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana Are you going to write the privacy policy yourself or use a sample one ?

**Comment by Kapileswar-Moharana** [comment]
> Include a privacy policy to inform users about how their data is collected and used.

@Aryankpoor m writing one the structure you can eddit the text as per your needd

**Comment by Aryankpoor** [comment]
ok

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Kaie PR merge krtee ho yarr.. harr barr tootaa footaa ataa haii ?
mere Local main akk type tumee Ak Type Look Out My Local View Once



https://github.com/Aryankpoor/Order-delivery/assets/129049677/423eabef-fd90-4f4a-a4a7-8547e37495c9

**Comment by Aryankpoor** [comment]
Privacy policy has not been added??

**Comment by Kapileswar-Moharana** [comment]
> Privacy policy has not been added??

@Aryankpoor Wait For 2 mins I am Raising the PR
